tracker/apps/accounts/urls.py
from django.urls import path
from .views import CreateAccountView, UpdateAccountView, ProfileView, CustomUserListView

app_name = "accounts"

urlpatterns = [
    path("create_account/", CreateAccountView.as_view(), name="create_account"),
    path("update_account/<pk>/", UpdateAccountView.as_view(), name="update_account"),
    path("list/", CustomUserListView.as_view(), name="user_list"),
    path("in/<str:slug>/", ProfileView.as_view(), name="profile"),
]

tracker/apps/core/urls.py
from django.urls import path

from .views import DashboardView, TicketListView, TicketView, TicketCreateView, TicketUpdateView

app_name = "core"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("tickets/", TicketListView.as_view(), name="ticket_list"),
    path("tickets/in/<pk>/", TicketView.as_view(), name="ticket"),
    path("tickets/create/", TicketCreateView.as_view(), name="ticket_create"),
    path("tickets/update/<pk>/", TicketUpdateView.as_view(), name="ticket_update"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings.base import DEBUG
from decouple import config

handler404 = "tracker.apps.core.views.custom_page_not_found_view"
handler500 = "tracker.apps.core.views.custom_error_view"
handler403 = "tracker.apps.core.views.custom_permission_denied_view"
handler400 = "tracker.apps.core.views.custom_bad_request_view"

urlpatterns = [
    path("accounts/", include("tracker.apps.accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("tracker.apps.core.urls")),
    path(config("ADMIN_URL") + "/", admin.site.urls),
]

if DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    from .settings.base import MEDIA_URL, MEDIA_ROOT

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

tracker/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from tracker.apps.core.utils import hash_filename
from django.utils import timezone


def profile_img_path(instance, filename):
    """
    Returns a path (filename included) for the uploaded image to be saved
    """
    timestamp = timezone.now()
    timestamp_string = timestamp.strftime("%Y-%m-%d_%H:%M:%S")
    return "profile_images/" + hash_filename(f"{instance.username}{timestamp_string}")


class CustomUser(AbstractUser):
    profile_image = models.ImageField(blank=True, upload_to=profile_img_path)
    position = models.CharField(max_length=50, null=True, blank=True)

    @property
    def open_tickets(self):
        return self.assigned_tickets.filter(status__name="Open").order_by("-pub_date").select_related()

    @property
    def closed_tickets(self):
        return self.assigned_tickets.filter(status__name="Closed").order_by("-pub_date")

    @property
    def best_name(self):
        if self.first_name and self.last_name:
            return " ".join([self.first_name, self.last_name])
        else:
            return self.username

    @classmethod
    def get_users_with_assignments(cls):
        uwa = []
        all = cls.objects.all().select_related()
        for user in all:
            tickets = user.assigned_tickets.filter(status__name="Open").order_by("-pub_date")
            if tickets:
                uwa.append((user, tickets[0]))
        return uwa

    def __str__(self):
        return self.username

tracker/apps/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ["username", "email", "profile_image", "position"]


class CustomUserChangeForm(UserChangeForm):
    password = None

    class Meta:
        model = CustomUser
        fields = ["first_name", "last_name", "position"]

tracker/apps/core/forms.py
from django.forms import ModelForm
from .models import TicketComment, TicketCommentFile


class TicketCommentForm(ModelForm):
    class Meta:
        model = TicketComment
        fields = ["content"]


class TicketCommentFileForm(ModelForm):
    class Meta:
        model = TicketCommentFile
        fields = ["file"]

tracker/apps/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .models import CustomUser
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.http import HttpResponse


class CustomUserListView(generic.ListView):
    model = CustomUser


class CreateAccountView(LoginRequiredMixin, CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "accounts/create_account.html"


class UpdateAccountView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    # model = CustomUser
    form_class = CustomUserChangeForm
    template_name = "accounts/update_account.html"
    queryset = CustomUser.objects.all()
    # fields = ["first_name", "last_name", "profile_image"]

    def get_success_url(self):
        return reverse_lazy("accounts:profile", kwargs={"slug": self.object.username})

    def test_func(self):
        """Users can only update their own profile"""
        return self.request.user.pk == int(self.kwargs["pk"])


class ProfileView(generic.DetailView):
    # for LoginRequiredMixin
    login_url = "login"
    # for Detail view
    model = CustomUser
    template_name = "accounts/profile.html"
    context_object_name = "user"
    slug_field = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        status = "Closed" if self.request.GET.get("status") == "Closed" else "Open"
        context["status"] = status
        context["tickets"] = self.object.assigned_tickets.filter(status__name=status).order_by("-pub_date")
        return context

tracker/apps/core/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseRedirect
from django.views import generic
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Ticket, TicketComment, TicketCommentFile, TicketStatus, TicketLabel
from .forms import TicketCommentForm, TicketCommentFileForm
from tracker.apps.accounts.models import CustomUser
from django.utils import timezone


class TicketListView(generic.ListView):
    model = Ticket
    ordering = ["status", "-pub_date"]

    def get_queryset(self):
        queryset = super().get_queryset()
        q = self.request.GET.get("q")
        if q:
            return queryset.filter(title__icontains=q)
        return queryset


class TicketDetailView(generic.DetailView):
    """
    This view processes all GET requests sent to TicketView.
    """

    model = Ticket
    context_object_name = "ticket"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comments = self.get_object().comments.all().order_by("pub_date").select_related()
        context["comments"] = comments
        if self.request.user.is_authenticated:
            context["comment_form"] = TicketCommentForm
            context["file_form"] = TicketCommentFileForm
            context["navigate_to_form"] = self._set_navigation()
            context["attachments"] = self._get_attachment_links()
        return context

    def _set_navigation(self):
        if "attachments" not in self.request.session:
            return False
        elif self.kwargs["pk"] not in self.request.session["attachments"]:
            return False
        else:
            return True

    def _get_attachment_links(self):
        print("the set att function gets executed")
        if "attachments" in self.request.session:
            attachments = self.request.session["attachments"]
            print("atts: ", attachments)
            print(self.kwargs["pk"])
            if self.kwargs["pk"] in attachments:
                return attachments[self.kwargs["pk"]]


class TicketCommentCreateView(LoginRequiredMixin, SingleObjectMixin, generic.FormView):
    """
    This view processes all POST requests sent to TicketView.
    """

    template_name = "core/ticket_detail.html"
    model = Ticket
    form_class = TicketCommentFileForm
    max_attachments = 3

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()  # for get_success_url kwargs
        if "content" in request.POST:
            # A comment was submitted
            form = TicketCommentForm(self.request.POST)
            comment = form.save(commit=False)
            comment.author = request.user
            comment.ticket = self.object
            comment.pub_date = timezone.now()
            comment.save()
            self.link_attachments(comment)
            return HttpResponseRedirect(self.get_success_url())
        elif "file" in request.FILES:
            # A file was submitted
            return super().post(request, *args, **kwargs)  # calls form_valid

    def form_valid(self, form):
        file = form.save(commit=False)
        file.name = str(self.request.FILES["file"])
        self.add_attachment(file)
        return super().form_valid(form)  # calls get_success_url

    def get_success_url(self):
        return reverse_lazy("core:ticket", kwargs={"pk": self.object.pk})

    def add_attachment(self, file):
        """
        Saves TicketCommentFile instance to db and creates
        attachment session variables associated with it
        """
        ticket_id = self.object.string_id
        if "attachments" not in self.request.session:
            self.request.session["attachments"] = {}
        attachtments = self.request.session["attachments"]
        if ticket_id not in attachtments:
            attachtments[ticket_id] = []
        if len(attachtments[ticket_id]) < self.max_attachments:
            # save to database
            file.save()
            # add to comment (session data)
            attachtments[ticket_id].append({"name": file.name, "id": file.id, "url": file.file.url})
            self.request.session["attachments"] = attachtments

    def link_attachments(self, comment):
        """
        Links attachements in database with the
        comment instance provided.

        - It fills the field "comment_id" in all the TicketCommentFile
         instances that belong to the provided TicketComment instance
        - It removes the attachment session variables for the
        ticket the comment instance belongs to.
        """
        if "attachments" in self.request.session:
            attachments = self.request.session["attachments"]
            ticket_id = self.object.string_id
            if ticket_id in attachments:
                for attachment in attachments[ticket_id]:
                    file = TicketCommentFile.objects.get(id=attachment["id"])
                    file.comment = comment
                    file.save()
                del attachments[ticket_id]
            self.request.session["attachments"] = attachments


class TicketView(generic.View):
    """
    View containing (a) the detail of the ticket,
    (b) the list of comments associated with that
    ticket, and (c) a form to submit a new comment
    """

    def get(self, request, *args, **kwargs):
        view = TicketDetailView.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = TicketCommentCreateView.as_view()
        return view(request, *args, **kwargs)


class DashboardView(TicketListView):
    template_name = "core/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["ticket_list_open"] = (
            Ticket.objects.filter(status__name="Open").filter(pub_date__lte=timezone.now()).order_by("-pub_date")
        )  # black formatter adds the parenthesis - https://github.com/psf/black/issues/620
        context["ticket_list_closed"] = (
            Ticket.objects.filter(status__name="Closed").filter(close_date__lte=timezone.now()).order_by("-pub_date")
        )
        context["ticket_this_week"] = Ticket.get_this_week_stats()
        context["ticket_avg_closing_time"] = Ticket.get_avg_closing_time()
        context["ticket_twelve_days_act"] = Ticket.get_twelve_days_activity()
        context["label_in_open"] = TicketLabel.get_amounts_in_open_tickets()
        context["user_amount"] = CustomUser.objects.count()
        context["user_list_with_assignments"] = CustomUser.get_users_with_assignments()
        return context


class TicketCreateView(LoginRequiredMixin, generic.CreateView):
    model = Ticket
    fields = ["assignees", "labels", "title", "content"]

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.status = TicketStatus.objects.get(name="Open")
        form.instance.pub_date = timezone.now()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("core:ticket", kwargs={"pk": self.object.pk})


class TicketUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Ticket
    fields = ["assignees", "labels", "title", "content", "progress", "status"]

    def get_success_url(self):
        return reverse_lazy("core:ticket", kwargs={"pk": self.object.pk})


def custom_page_not_found_view(request, exception):
    return render(request, "errors/404.html", {})


def custom_error_view(request, exception=None):
    return render(request, "errors/500.html", {})


def custom_permission_denied_view(request, exception=None):
    return render(request, "errors/403.html", {})


def custom_bad_request_view(request, exception=None):
    return render(request, "errors/400.html", {})

tracker/templates/_identify_image.html
{% comment %}
    Usage: {% include "_identify_image.html"  with user=user%}
{% endcomment %}
{% load static %}
{% if user.profile_image %}
    {{ user.profile_image.url }}
{% else %}
    {% static "images/default_profile_picture.png" %}
{% endif %}

tracker/templates/_identify_position.html
{% comment %}
Usage: {% include "_identify_position.html"  with user=user%}
{% endcomment %}
{% if user.position %}
    {{user.position}}
{% else %}
    Developer
{% endif %}

tracker/templates/_nav.html
{% load static %}
    <nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex align-items-top flex-row">
      <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
        <div class="me-3">
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-bs-toggle="minimize">
            <span class="icon-menu"></span>
          </button>
        </div>
        <div>
          <a class="navbar-brand brand-logo" href="{%url 'core:dashboard'%}">
            <!-- <img src="{% static "images/logo.svg" %}" alt="logo" /> -->
            <img style="width=100%; height: 90%;" src="{% static "images/logo.png" %}" alt="logo" />
          </a>
          <a class="navbar-brand brand-logo-mini" href="{%url 'core:dashboard'%}">
            <!-- <img src="{% static "images/logo-mini.svg" %}" alt="logo" /> -->
            <img src="{% static "images/logo-mini.png" %}" alt="logo" />
          </a>
        </div>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-top"> 
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
          <li class="nav-item font-weight-semibold d-none d-lg-block ms-0">
            <h1 class="welcome-text">Welcome, <span class="text-black fw-bold">{{ user.best_name }}</span></h1>
            <h3 class="welcome-sub-text">Your team stats are ready for review.</h3>
          </li>          
          {% else %}
          <li class="nav-item font-weight-semibold d-none d-lg-block ms-0">
            <h1 class="welcome-text">Welcome, <span class="text-black fw-bold">Guest</span></h1>
            <h3 class="welcome-sub-text">Thanks for visiting. <a href="{%url "login"%}" style="color: inherit; text-decoration: none;">Sign in</a> for full access to CRUD operations.</h3>
          </li>
          {% endif %}          
        </ul>
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            {% include "_ticket_search.html" %}
          </li>
          <li class="nav-item">
            <form action="{% url 'core:ticket_create'%}" method="get">
              <button class="btn btn-primary btn-md text-white mx-2" type="submit">
                <strong>Create</strong>
            </button>
          </form>            
          </li>
          <li class="nav-item dropdown d-none d-lg-block user-dropdown">
            <a class="nav-link" id="UserDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
              {% if request.user.profile_image %}
              <img class="img-xs rounded-circle" src="{{ request.user.profile_image.url }}" alt="Profile image"> </a>
              {% else %}
              <img class="img-xs rounded-circle" src="{% static "images/default_profile_picture.png" %}" alt="Profile image"> </a>
              {% endif %}
              <!-- <img class="img-xs rounded-circle" src="{% static "images/faces/face8.jpg" %}" alt="Profile image"> </a> -->
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
              <div class="dropdown-header text-center">
                <img class="img-xs rounded-circle" src="{% include "_identify_image.html"  with user=user%}" alt="Profile image">


                {% if request.user.is_authenticated %}
                  <p class="mb-1 mt-3 font-weight-semibold">
                    {{request.user.best_name}}
                  </p>
                {% else %}
                  <p class="mb-1 mt-3 font-weight-semibold">
                    Guest
                  </p>
                {% endif %}
                <!-- <p class="fw-light text-muted mb-0">allenmoreno@gmail.com</p> -->
                <!-- <img class="img-md rounded-circle" src="{% static "images/faces/face8.jpg" %}" alt="Profile image"> -->
              </div>
              {% if request.user.is_authenticated %}
                <a href="{%url "accounts:profile" request.user%}" class="dropdown-item"><i class="dropdown-item-icon mdi mdi-account-outline text-primary me-2"></i>My Profile</a>
                <a href="{%url "accounts:update_account" request.user.id%}" class="dropdown-item"><i class="dropdown-item-icon mdi mdi-account-multiple-outline text-primary me-2"></i>Update Account</a>
                <a href="{%url "password_change" %}" class="dropdown-item"><i class="dropdown-item-icon mdi mdi-account-key text-primary me-2"></i>Change Password</a>
                <a href="{%url "logout"%}" class="dropdown-item"><i class="dropdown-item-icon mdi mdi-power text-primary me-2"></i>Sign Out</a>
              {%else%}
                <a href="{%url "login"%}" class="dropdown-item"><i class="dropdown-item-icon mdi mdi-power text-primary me-2"></i>Sign In</a>
              {% endif %}
              <!-- <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-message-text-outline text-primary me-2"></i> Messages</a> -->
              <!-- <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-calendar-check-outline text-primary me-2"></i> Activity</a> -->
              <!-- <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-help-circle-outline text-primary me-2"></i> FAQ</a> -->
            </div>
          </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-bs-toggle="offcanvas">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </nav>

tracker/templates/_nav_off_canvas.html
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="{%url 'core:dashboard'%}">
              <i class="mdi mdi-grid-large menu-icon"></i>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'core:ticket_list'%}">
              <i class="menu-icon mdi mdi-card-text-outline"></i>
              <span class="menu-title">Issues</span>
            </a>
          </li>       
          <li class="nav-item">
            <a class="nav-link" href="{%url 'accounts:user_list'%}">
              <i class="mdi mdi-account-multiple-outline menu-icon"></i>
              <span class="menu-title">Team Workload</span>
            </a>
          </li>                       
        </ul>
      </nav>

tracker/templates/_photo_name_div.html
{% comment %}
    Usage: {% include "_photo_name_div.html"  with user=user%}
{% endcomment %}
<div  class="d-flex ">
    <img src="{% include "_identify_image.html"  with user=user%}" alt="">
    <div>
        <a href="{%url "accounts:profile" user%}" style="color: inherit; text-decoration: none;">
            <h6>{{user.best_name}}</h6>
        </a>
      <p>
        {% include "_identify_position.html"  with user=user%}
      </p>
    </div>
  </div>

tracker/templates/_progress_div.html
<div>
    <div class="d-flex justify-content-between align-items-center mb-1 max-width-progress-wrap">
      <!-- number always green -->
      <p class="text-success">{{ ticket.progress }}%</p>
    </div>
    {% if ticket.stage == "Pending" %}
    <div class="progress progress-md">
      <div class="progress-bar bg-danger" role="progressbar" style="width: {{ ticket.progress }}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
    </div>                                        
    {% elif ticket.stage == "In Progress" %}
    <div class="progress progress-md">
      <div class="progress-bar bg-warning" role="progressbar" style="width: {{ ticket.progress }}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
    {% elif ticket.stage == "Close to Completion" %}
    <div class="progress progress-md">
      <div class="progress-bar bg-success" role="progressbar" style="width: {{ ticket.progress }}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
    {% elif ticket.stage == "Closed" %}
    <div class="progress progress-md">
      <div class="progress-bar bg-success" role="progressbar" style="width: {{ ticket.progress }}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
    </div>    
    {% else %}
    <p>progress-bar</p>
    <p>stage: {{ticket.stage}}</p>
    {% endif %}
</div>

tracker/templates/_stage_div.html
{% if ticket.stage == "Pending" %}
<div class="badge badge-opacity-danger">Pending</div>
{% elif ticket.stage == "In Progress" %}
<div class="badge badge-opacity-warning">In progress</div>  
{% elif ticket.stage == "Close to Completion" %}
  <div class="badge badge-opacity-success">Close to Completion</div>
{% elif ticket.stage == "Closed" %}
<div class="badge badge-opacity-light">Closed</div>
{% endif %}

tracker/templates/_ticket_search.html
<form class="search-form" action="{% url "core:ticket_list" %}" method="GET">
    <i class="icon-search"></i>
    <input type="search" class="form-control" placeholder="Search Here" title="Search here" name="q">
</form>

tracker/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Issue Tracker </title>
  <!-- plugins:css -->
  <!-- OK for crispy forms-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- OK -->
  <link rel="stylesheet" href="{% static "vendors/feather/feather.css" %}">
  <!-- OK -->
  <link rel="stylesheet" href="{% static "vendors/mdi/css/materialdesignicons.min.css" %}">
  <!-- OK (checked arrow)-->
  <link rel="stylesheet" href="{% static "vendors/ti-icons/css/themify-icons.css" %}">
  <link rel="stylesheet" href="{% static "vendors/typicons/typicons.css" %}">
  <link rel="stylesheet" href="{% static "vendors/simple-line-icons/css/simple-line-icons.css" %}">
  <link rel="stylesheet" href="{% static "vendors/css/vendor.bundle.base.css" %}">
  <!-- endinject -->
  <!-- OK - prevents glitch - Plugin css for this page -->
  <link rel="stylesheet" href="{% static "vendors/datatables.net-bs4/dataTables.bootstrap4.css" %}">
  <link rel="stylesheet" href="{% static "js/select.dataTables.min.css" %}">
  <!-- End plugin css for this page -->
  <!-- OK inject:css -->
  <link rel="stylesheet" href="{% static "css/vertical-layout-light/style.css" %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{% static "images/favicon.png" %}" />
</head>
<body>
  <div class="container-scroller">
    <!-- PLACEHOLDER - Here used to be the pro banner -->
    <!-- partial:partials/_navbar.html -->
    {% include './_nav.html' %}
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- partial:partials/_settings-panel.html -->
      <!-- PLACEHOLDER - here it was theme-settings-wrapper -->
      <!-- PLACEHOLDER - here it was id="right-sidebar" class="settings-panel" -->
      <!-- partial -->
      <!-- partial:partials/_sidebar.html -->

      {% include './_nav_off_canvas.html' %}
      <!-- partial -->
      <div class="main-panel">
        <!-- PLACEHOLDER FOR BLOCK - BLOCK NEEDS TO BE IN A CONTENT WRAPPER -->
        <div class="content-wrapper">
          {% block content %}{% endblock %}
        </div>        
        <!-- content-wrapper ends -->
        <!-- partial:partials/_footer.html -->
        <footer class="footer">
          <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Project by Martin Poncio. Find Source Code in <a href="https://github.com/lmponcio/Django-Issue-Tracker" target="_blank">Github</a>.</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Django Issue Tracker Web App.</span>
          </div>
        </footer>
        <!-- partial -->
      </div>
      <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->

  <!-- OK - Main graph - plugins:js -->
  <script src="{% static "vendors/js/vendor.bundle.base.js" %}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page -->
  <!-- OK -->
  <script src="{% static "vendors/chart.js/Chart.min.js" %}"></script>
  <!-- <script src="{% static "vendors/bootstrap-datepicker/bootstrap-datepicker.min.js" %}"></script> -->
  <script src="{% static "vendors/progressbar.js/progressbar.min.js" %}"></script>

  <!-- End plugin js for this page -->
  <!-- inject:js -->
  <!-- <script src="{% static "js/off-canvas.js" %}"></script> -->
  <!-- OK -->
  <script src="{% static "js/hoverable-collapse.js" %}"></script>
  <!-- OK -->
  <script src="{% static "js/template.js" %}"></script>
  <script src="{% static "js/settings.js" %}"></script>
  <!-- <script src="{% static "js/todolist.js" %}"></script> -->
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="{% static "js/jquery.cookie.js" %}" type="text/javascript"></script>
  <!-- OK bar graph -->
  <script src="{% static "js/dashboard.js" %}"></script>
  <script src="{% static "js/Chart.roundedBarCharts.js" %}"></script>
  <!-- End custom js for this page-->
</body>

</html>

tracker/templates/progress_div.html
<div>
    <div class="d-flex justify-content-between align-items-center mb-1 max-width-progress-wrap">
      <!-- PROGRESS NUMBER ALWAYS GREEN -->
      <p class="text-success">{{ ticket.progress }}%</p>
    </div>
    {% if ticket.stage == "Pending" %}
    <div class="progress progress-md">
      <div class="progress-bar bg-danger" role="progressbar" style="width: {{ ticket.progress }}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
    </div>                                        
    {% elif ticket.stage == "In Progress" %}
    <div class="progress progress-md">
      <div class="progress-bar bg-warning" role="progressbar" style="width: {{ ticket.progress }}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
    {% elif ticket.stage == "Close to Completion" %}
    <div class="progress progress-md">
      <div class="progress-bar bg-success" role="progressbar" style="width: {{ ticket.progress }}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
    {% endif %}
</div>

tracker/templates/stage_div.html
{% if ticket.stage == "Pending" %}
<div class="badge badge-opacity-danger">Pending</div>
{% elif ticket.stage == "In Progress" %}
<div class="badge badge-opacity-warning">In progress</div>  
{% elif ticket.stage == "Close to Completion" %}
  <div class="badge badge-opacity-success">Close to Completion</div>
{% endif %}