tracker/apps/accounts/urls.py
from django.urls import path
from .views import CreateAccountView, UpdateAccountView, ProfileView, CustomUserListView

app_name = "accounts"

urlpatterns = [
    path("create_account/", CreateAccountView.as_view(), name="create_account"),
    path("update_account/<pk>/", UpdateAccountView.as_view(), name="update_account"),
    path("list/", CustomUserListView.as_view(), name="user_list"),
    path("in/<str:slug>/", ProfileView.as_view(), name="profile"),
]

tracker/apps/core/urls.py
from django.urls import path

from .views import DashboardView, TicketListView, TicketView, TicketCreateView, TicketUpdateView

app_name = "core"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("tickets/", TicketListView.as_view(), name="ticket_list"),
    path("tickets/in/<pk>/", TicketView.as_view(), name="ticket"),
    path("tickets/create/", TicketCreateView.as_view(), name="ticket_create"),
    path("tickets/update/<pk>/", TicketUpdateView.as_view(), name="ticket_update"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings.base import DEBUG
from decouple import config

handler404 = "tracker.apps.core.views.custom_page_not_found_view"
handler500 = "tracker.apps.core.views.custom_error_view"
handler403 = "tracker.apps.core.views.custom_permission_denied_view"
handler400 = "tracker.apps.core.views.custom_bad_request_view"

urlpatterns = [
    path("accounts/", include("tracker.apps.accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("tracker.apps.core.urls")),
    path(config("ADMIN_URL") + "/", admin.site.urls),
]

if DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    from .settings.base import MEDIA_URL, MEDIA_ROOT

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

tracker/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from tracker.apps.core.utils import hash_filename
from django.utils import timezone


def profile_img_path(instance, filename):
    """
    Returns a path (filename included) for the uploaded image to be saved
    """
    timestamp = timezone.now()
    timestamp_string = timestamp.strftime("%Y-%m-%d_%H:%M:%S")
    return "profile_images/" + hash_filename(f"{instance.username}{timestamp_string}")


class CustomUser(AbstractUser):
    profile_image = models.ImageField(blank=True, upload_to=profile_img_path)
    position = models.CharField(max_length=50, null=True, blank=True)

    @property
    def open_tickets(self):
        return self.assigned_tickets.filter(status__name="Open").order_by("-pub_date").select_related()

    @property
    def closed_tickets(self):
        return self.assigned_tickets.filter(status__name="Closed").order_by("-pub_date")

    @property
    def best_name(self):
        if self.first_name and self.last_name:
            return " ".join([self.first_name, self.last_name])
        else:
            return self.username

    @classmethod
    def get_users_with_assignments(cls):
        uwa = []
        all = cls.objects.all().select_related()
        for user in all:
            tickets = user.assigned_tickets.filter(status__name="Open").order_by("-pub_date")
            if tickets:
                uwa.append((user, tickets[0]))
        return uwa

    def __str__(self):
        return self.username

tracker/apps/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ["username", "email", "profile_image", "position"]


class CustomUserChangeForm(UserChangeForm):
    password = None

    class Meta:
        model = CustomUser
        fields = ["first_name", "last_name", "position"]

tracker/apps/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .models import CustomUser
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.http import HttpResponse


class CustomUserListView(generic.ListView):
    model = CustomUser


class CreateAccountView(LoginRequiredMixin, CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "accounts/create_account.html"


class UpdateAccountView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    # model = CustomUser
    form_class = CustomUserChangeForm
    template_name = "accounts/update_account.html"
    queryset = CustomUser.objects.all()
    # fields = ["first_name", "last_name", "profile_image"]

    def get_success_url(self):
        return reverse_lazy("accounts:profile", kwargs={"slug": self.object.username})

    def test_func(self):
        """Users can only update their own profile"""
        return self.request.user.pk == int(self.kwargs["pk"])


class ProfileView(generic.DetailView):
    # for LoginRequiredMixin
    login_url = "login"
    # for Detail view
    model = CustomUser
    template_name = "accounts/profile.html"
    context_object_name = "user"
    slug_field = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        status = "Closed" if self.request.GET.get("status") == "Closed" else "Open"
        context["status"] = status
        context["tickets"] = self.object.assigned_tickets.filter(status__name=status).order_by("-pub_date")
        return context

tracker/apps/accounts/templates/accounts/createAccount.html
{% extends 'base.html' %}
{% block content %}
    <h2>Create Account</h2>
    <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Account</button>
    </form>
{% endblock %}

tracker/apps/accounts/templates/accounts/create_account.html
{% extends 'base.html' %}
{% block content %}
    <h2>Create Account</h2>
    <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Account</button>
    </form>
{% endblock %}

tracker/apps/accounts/templates/accounts/customuser_list.html
{% extends "base.html" %}

{% block content %}

{% if object_list %}

<div class="row">
    <div class="col-lg-12 grid-margin">
        <div class="card">
        <div class="card-body">
            <h4 class="card-title card-title-dash">Team Workload</h4>
            <div class="table-responsive mt-1">
            <table class="table select-table">
                <thead>
                <tr>
                    <th>Team Member</th>
                    <th>Issue ID</th>     
                    <th>Content</th>     
                    <th>Created By</th>     
                    <th>Date Opened</th>
                    <th>Progress</th>
                    <th>Status</th>                    
                </tr>
                </thead>
                <tbody>
                {% for user in object_list %}
                    <tr>
                    <!-- Only users that have open tickets will be shown -->
                    {% for ticket in user.open_tickets %}
                        {% if forloop.first %}
                        <td>
                            {% include "_photo_name_div.html"  with user=user%}                        
                        </td>
                        {% else %}
                        <td></td>
                        {% endif %}
                        <td>
                            <a href="{%url "core:ticket" ticket.id%}" style="color: inherit; text-decoration: none;">
                                <h6>{{ticket.id}}</h6>
                            </a>
                        </td>
                        <td>
                            <a href="{%url "core:ticket" ticket.id%}" style="color: inherit; text-decoration: none;">
                                <h6>{{ticket.title}}</h6>
                                <p>{{ticket.content|slice:":20"}} ...</p>                            
                            </a>
                        </td>
                        <td>
                            <!-- created by -->
                            <a href="{%url "accounts:profile" ticket.author%}" style="color: inherit; text-decoration: none;">
                                <p>{{ticket.author.best_name}}</p>                            
                            </a>
                        </td>
                        <td>
                            <!-- date opened -->
                            <p>{{ticket.pub_date}}</p>
                        </td>
                        <td>
                            <!-- progress -->
                            {% include "_progress_div.html" with ticket=ticket %}
                        </td>
                        <td>
                            <!-- status -->
                            {% include "_stage_div.html" with ticket=ticket %}
                        </td>
                    </tr>
                    {%endfor%}
                {%endfor%}
                </tbody>
            </table>
            </div>
        </div>
        </div>
    </div>
</div>

{% else %}
    <p>No Tickets in Database</p>
{% endif %}

{% endblock content%}

tracker/apps/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-lg-4 grid-margin">
            <div class="card">
            <div class="card-body mt-2">
                <div class="text-center">
                    <img class="w-50 img-md rounded-circle" src="{% include "_identify_image.html"  with user=user%}" alt="">
                </div>
                <div class="text-center">
                    <h4 class="display-5 mt-3">
                        {{user.best_name}}
                    </h4>
                    <p class="card-description">
                        {% include "_identify_position.html"  with user=user%}
                    </p>
                </div>
                <div class="text-center row d-flex justify-content-center mt-1">
                    <form action="{% url 'accounts:profile' user %}" method="get">
                        <button type="submit" name="status" value="Open" class="w-75 my-2 btn btn-secondary btn-rounded">Open Issues</button>            
                    </form>
                    <form action="{% url 'accounts:profile' user %}" method="get">
                        <button type="submit" name="status" value="Closed" class="w-75 my-2 btn btn-secondary btn-rounded">Closed Issues</button>
                    </form>
                </div>
            </div>
            </div>
        </div>
        <div class="col-lg-8 grid-margin">
            <div class="card">
            <div class="card-body">
                <h4 class="card-title card-title-dash">{{status}} Assigned Issues</h4>
                <div class="table-responsive mt-1">
                <table class="table select-table">
                    <thead>
                    <tr>
                        <th>
                        ID
                        </th>
                        <th>
                        Content
                        </th>                    
                        <th>
                        Date Opened
                        </th>
                        <th>
                        Progress
                        </th>
                        <th>
                        Status
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for ticket in tickets %}
                    <tr>
                        <td class="py-1">
                            <a href="{%url "core:ticket" ticket.id%}" style="color: inherit; text-decoration: none;">
                                <h6>{{ticket.id}}</h6>
                            </a>
                        </td>
                        <td>
                            <a href="{%url "core:ticket" ticket.id%}" style="color: inherit; text-decoration: none;">
                                <h6>{{ticket.title}}</h6>
                                <p>{{ticket.content|slice:":35"}} ...</p>                        
                            </a>
                        </td>   
                        <td>
                            <p>{{ticket.pub_date}}</p>                        
                        </td>
                        <td>
                            {% include "_progress_div.html" with ticket=ticket %}                                        
                        </td>      
                        <td>
                            {% include "_stage_div.html" with ticket=ticket %}
                        </td>                                                      
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div>
    </div>
{% endblock content%}

{% comment block %}
    <h2>Your profile, {{user.username}}</h2>
    <p>{{user.email}}</p>

    <ul>
    {% for ticket in user.created_tickets.all %}
        <li>{{ticket.title}}</li>
    {% endfor %}
    </ul>
{% endcomment %}

tracker/apps/accounts/templates/accounts/update_account.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container-scroller">
    <div class="container-fluid mt-5">
        <div class="content-wrapper d-flex align-items-center auth px-0">
            <div class="row w-100 mx-0">
                <div class="col-lg-4 mx-auto">
                    <div class="auth-form-light text-left py-5 px-4 px-sm-5">
                        <div class="brand-logo">
                            <img src="{% static "images/logo.png" %}" alt="logo" />
                          </div>                    
                        <h3 class="mb-3">Update Account</h3>
                        <form method="post" enctype='multipart/form-data'>
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type="submit" class="btn btn-primary">Update<i class="fas fa-comments"></i></button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}